apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: database-service
spec:
  selector:
    app: database-service
  ports:
    - port: 8081
      targetPort: 8081
  type: NodePort
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: database-service-config
data:
  application.properties:
    spring.data.mongodb.uri=mongodb://adminlocal:gpocus8gwu7b9w2pl93lit2x77vo08@10.0.1.81:27017/admin?authSource=admin&retryWrites=true&loadBalanced=false&connectTimeoutMS=10000&authMechanism=SCRAM-SHA-1
    server.port: "8081"
    logging.level.org.springframework.data.mongodb: "DEBUG"
    spring.application.name=database-service
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-service
  labels:
    app: database-service
spec:
  selector:
    matchLabels:
      app: database-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database-service
        tier: database-service
    spec:
      serviceAccountName: default
      containers:
        - image: 774305578623.dkr.ecr.ap-southeast-1.amazonaws.com/database-service-luan:dev
          name: database-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: db-service
          volumeMounts:
            - name: config
              mountPath: /app/config
          env:
            - name: SPRING_CONFIG_LOCATION  
              value: file:/app/config/
      volumes:
        - name: config
          configMap:
            name: database-service-config
             


 